# Generated by Django 4.1.3 on 2022-11-05 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anesthesiologist', '0001_initial'),
        ('pateint', '0001_initial'),
        ('sergeon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pateingsurgeryscheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_code', models.CharField(max_length=20)),
                ('schedule_name', models.CharField(max_length=100)),
                ('schedule_date', models.DateTimeField()),
                ('schedule_status', models.BooleanField()),
                ('anesthesiologist_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anesthesiologist.anesthesiologist')),
                ('pateint_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pateint.patient')),
                ('surgeon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sergeon.surgeon')),
            ],
            options={
                'db_table': 'pateintsurgeryschedule',
            },
        ),
    ]
