# Generated by Django 4.1.3 on 2022-11-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sergeon', '0001_initial'),
        ('anesthesiologist', '0001_initial'),
        ('pateint', '0001_initial'),
        ('pateintsurgeryschedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='anesthesiologist_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anesthesiologist.anesthesiologist'),
        ),
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='pateint_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pateint.patient'),
        ),
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='surgeon_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sergeon.surgeon'),
        ),
    ]
