# Generated by Django 4.1.3 on 2022-11-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anesthesiologist', '0001_initial'),
        ('sergeon', '0001_initial'),
        ('pateint', '0001_initial'),
        ('pateintsurgeryschedule', '0003_alter_pateingsurgeryscheduler_anesthesiologist_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='anesthesiologist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='anesthesiologist.anesthesiologist'),
        ),
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='pateint_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pateint.patient'),
        ),
        migrations.AlterField(
            model_name='pateingsurgeryscheduler',
            name='surgeon_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sergeon.surgeon'),
        ),
    ]
