# Generated by Django 4.1.3 on 2022-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sg_id', models.CharField(max_length=20)),
                ('sg_code', models.CharField(max_length=20)),
                ('sg_name', models.CharField(max_length=100)),
                ('sg_email', models.EmailField(max_length=254)),
                ('sg_contact', models.CharField(max_length=15)),
                ('sg_address', models.CharField(max_length=250)),
                ('sg_highest_degree', models.CharField(max_length=150)),
                ('sg_office_name', models.CharField(max_length=150)),
                ('sg_status', models.BooleanField()),
            ],
            options={
                'db_table': 'infosurgeon',
            },
        ),
    ]
